### PR TITLE
Increase speed based on score and owls

### PR DESCRIPTION
**Pull request by MLXXXp**
This change keeps track of the number of owls that have been created and increases the frame rate of the game based on your score and the number of owls.

You could fiddle with the algorithm in new function _setSpeed()_ if desired.

### CODE REVIEW

**Comment by andrewlow** [comment]
Thanks for taking the time to make a change. Let me just play test it a bit before accepting. 

I agree that the game is 'overly easy' -- but I was surprised when I gave it to others to play that they actually struggled to get more than a few points. 

I want the end result to be very accessible - so that even a young child can play successfully for a little while. However, for more experienced gamers -- increasing difficulty is a win, but it should increase after some amount of play (ie: endurance is part of the challenge).

Again, super that you made a code change -- thanks! I just want to make sure the setSpeed() algorithm doesn't make the game too difficult.

**Comment by MLXXXp** [comment]
The algorithm I used works pretty good for me but, like I said, you may wish to change it.

If you want to get creative, you could add a "easy, normal, hard" selection menu which would alter the speed algorithm. It could appear at the start and also if the _B_ button is pressed before starting a new game.

For some "expert" players, the game might always remain too easy, since at some point the desired frame rate exceeds the processing power.

**Comment by andrewlow** [comment]
Other simple 'make it harder' tweaks would be to speed up the rate at which the owl flight path is stepped through -- incoming owls could easily move 2x faster

**Comment by MLXXXp** [comment]
I've realised that the parameter passed to _setFrameRate()_ is only an 8 bit value, so I've added another commit to this pull request with changes in _setSpeed()_ to prevent the value from overflowing/wrapping.

**Comment by andrewlow** [comment]
Sorry it's taken me way too long to get back to this. The holidays happened.

The changes you've made, work as described. I think it gets too hard too quickly. Maybe I'm a terrible gamer, but getting a score up over 20 seems pretty hard now.

I'm not sure about driving the frame rate higher is the right way to make the game harder (but I'll grant that it works well). At a score of 50 I had a frame rate of 196.. 

```
diff --git a/flappyhalloween.ino b/flappyhalloween.ino
index 13c1fef..c7a1645 100644
--- a/flappyhalloween.ino
+++ b/flappyhalloween.ino
@@ -19,6 +19,7 @@
 Arduboy arduboy;

 bool start = false;
+int rate=60;
 int score = 0;
 int bestScore = 0;
 char scoreString[32];
@@ -253,7 +254,9 @@ void loop()
     arduboy.setCursor(72, 0);
     sprintf(scoreString, "%d", score);
     arduboy.print(scoreString);
-
+    arduboy.setCursor(95, 0);
+    sprintf(scoreString, "%d", rate);
+    arduboy.print(scoreString);


     arduboy.display();
@@ -276,7 +279,7 @@ void loop()

 // Set the speed of the game
 void setSpeed() {
-  int rate = 60 + (score * 2) + (owlCount * 3);
+  rate = 60 + (score * 2) + (owlCount * 3);
   arduboy.setFrameRate(rate > 255 ? 255 : rate);
 }

```

Play testing against the 'stock' state of the game shows that it really really needs some sort of skill increase built in.

**Comment by andrewlow** [comment]
So I thought I'd try out some alternatives - doubling the rate of the owl after your score hits 10 (and every 10 after that)

```
diff --git a/flappyhalloween.ino b/flappyhalloween.ino
index a869171..37facab 100644
--- a/flappyhalloween.ino
+++ b/flappyhalloween.ino
@@ -120,15 +120,16 @@ void loop()
       }
     }

+
     if( owlActive) {
-      if(0 == (frame % owlSpeed)) {
-        owlX--;
+      if(0 == (frame % owlSpeed)) {        
+        owlX = owlX - (1 + (score / 10));
       }

       // eventually we want a set of random flights to pick from
       owlY = flight1[flightOffset + owlX + 16];

-      if(owlX == -16) { // owl is offscreen
+      if(owlX <= -16) { // owl is offscreen
         owlActive = false;
       }
```

Unfortunately there is a big notch once you hit 10. Maybe frame rate increase isn't so bad. The 'right' answer might be a slightly gentler increase in frame rate as your score / owls increase.

**Comment by andrewlow** [comment]
Using the score \* 2 to increase the chances you get an owl does make it harder (but slowly)

```
@@ -114,21 +114,22 @@ void loop()
     bugFrame = frame % bugRate;

     if( !owlActive ) {
-      if(2 > random(1,300)) { // 2 in 300 chances of an owl becoming active
+      if(2 > random(1,(300 - (score * 2))) { // 2 in 300 chances of an owl becoming active
         owlActive = true;
         owlX = 128;
       }
     }
```

These experiments have changed my mind on the frame rate increase. 

I'm thinking:
- no speed tweaks until we have a score of 10
- a more gradual frame rate increase
- "stepped" increases on the frequency of owls (score 25, 50, 75?)
- possibly double the owl rate if you top 100..

**Comment by MLXXXp** [comment]
The speed increase is quite subtle now but it still gets more difficult, so the game doesn't go on forever if you're good.

**Comment by MLXXXp** [comment]
The pull request has been replaced by #4 to allow a clean merge.

**Pull request closed without merging**
